#!/bin/sh

start() {
    sleep 10
    export XDG_RUNTIME_DIR=/tmp/weston
    mkdir -p $XDG_RUNTIME_DIR
    chmod 700 $XDG_RUNTIME_DIR
    weston --log /log.txt &
    sleep 1
    export WAYLAND_DISPLAY=wayland-1
    #URL="https://www.google.ch"
    URL="http://192.168.0.222:3000/d/574d7f7f-bc36-4dce-abf0-c2ddb74a452b/power?orgId=1&from=now-30m&to=now&timezone=browser&refresh=5s&kiosk=1"
    cog -P wl "$URL" &
    sleep 2
    killall cog
    export COG_PLATFORM_WL_VIEW_FULLSCREEN=1
    cog -P wl "$URL" &
}

stop() {
    killall cog
    killall weston
}

 

restart() {
      stop
      sleep 1
      start
}

 

case "$1" in
      start|stop|restart)
              "$1";;
      reload)
              # Restart, since there is no true "reload" feature.
              restart;;
      *)
              echo "Usage: $0 {start|stop|restart|reload}"
              exit 1
esac