#!/bin/sh

SERVER="192.168.0.22"
SERVER="192.168.1.1"
URL="http://${SERVER}:3000/d/574d7f7f-bc36-4dce-abf0-c2ddb74a452b/power?orgId=1&from=now-30m&to=now&timezone=browser&refresh=5s&kiosk=1"

start() {
  /start.sh
}

stop() {
  killall cog
  killall weston
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
start | stop | restart)
  "$1"
  ;;
reload)
  # Restart, since there is no true "reload" feature.
  restart
  ;;
*)
  echo "Usage: $0 {start|stop|restart|reload}"
  exit 1
  ;;
esac
